### ISSUE TITLE
I find something wrong about the time of a paper

### ISSUE THREAD

**Issue by 1zn** [zzw922cn/awesome-speech-recognition-speech-synthesis-papers#6]
this paper：
Review of Tdnn (time Delay Neural Network) Architectures for Speech Recognition(2014), Masahide Sugiyamat et al.   
I search it in the search engine, and I find it come from ' IEEE International Sympoisum on Circuits & Systems 1991 '

**Comment by zzw922cn** [comment]
OK， thank you
